### ISSUE TITLE
Feedback for asana-shift

### ISSUE THREAD

**Issue by markyao6275** [Asana/asana-shift#1]
**Small Stuff**:
https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/asana.ts#L51
- I don't follow why these are called "packets". Maybe there's a better name?

https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/asana.ts#L102
- 10 should probably be a named constant (and possibly parametrized) here, which would also have the side benefit of you being able to give it a variable name, thus enhancing clarity

**Medium Stuff**:
https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/shift.ts#L73
- Indexing into the return of `asana.getProject` looks odd. Probably better that `asana.getProject` returns an object with `"project"` and `"tasks"` keys, or better yet, return a "project" object with "tasks" as one of the keys

https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/shift.ts#L86
- So if the user enters a `shiftAmount` of 0, we'll let that through and make all the API calls?

**Larger Stuff**:
https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/shift.ts#L14
- Since this is intended to be used by customers, it might be worth documenting how edge-casey things like rounding will work

https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/shift.ts#L53
- It seems like even if a task doesn't need to be shifted, we're still going to make an API call (that effectively doesn't change anything). It might be worth the performance benefit to not issue API calls for the tasks that aren't going to be shifted

https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/asana.ts#L84
- You should use pagination here to not overwhelm the API + not error on larger projects, where the API will require pagination

**Suggestions/Questions**:
https://github.com/Asana/asana-shift/blob/7338b886889d82ab41627dd20aeeb89f27ceb9fd/src/asana.ts#L122
- Might be worth catching things like the RateLimited or 5xx status codes and retrying appropriately.

Also, any reason that you didn't use the client library? I believe that'll make it easy to handle

**Comment by notitatall** [comment]
Thanks @markyao6275 

**Small stuff**
1. Point taken with "packets", I've changed it to "batches" which is hopefully more expressive.
2. I've parametrized 10 here and just made the default argument 10.

**Medium stuff**
1. Yeah good catch there, I knew that indexing in felt weird when I typed that but it didn't immediately occur to me that I could just return a nicely formatted object instead. I'm doing that now.

2. We now throw if the user enters a 0 shift amount

**Large stuff** 
1. We don't work with times at all so I don't think moment would ever have to round if we're going off of the project due date. I've added some documentation to specify that if you provide a float shift amount, the script will always floor it.

2. I don't believe this case is possible. The script stops execution and informs the user if the shift amount is 0 or the project due date and latest task due date are equal. If the project due date and latest task due date are not equal than all tasks ought to shift either backwards or forwards.

3. Good call, I've implemented pagination so we can work with larger projects.

I didn't use with the client library here because I wasn't certain it would give us safe rate limiting with the batch API (to the client, I imagine it seems we're making 1 request while we are actually making up to 10).
